server:
  port: 8080
spring:
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-file-size: 5GB #设置单个文件最大长度
      max-request-size: 10GB #最大请求文件的大小
  application:
    name: server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ACloud?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.adaa7.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
